server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/v1/user/**
        - id: NOTIFICATION
          uri: lb://NOTIFICATION
          predicates:
            - Path=/v1/notification/**

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka